# Generated by Django 2.0.5 on 2018-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbms_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('a', models.CharField(max_length=1000)),
                ('b', models.CharField(max_length=1000)),
                ('c', models.CharField(max_length=1000)),
                ('d', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'DBMS_questions',
            },
        ),
        migrations.CreateModel(
            name='dbms_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, null=True)),
                ('regno', models.CharField(max_length=264, null=True)),
                ('year', models.CharField(choices=[('firstyear', 'I'), ('secondyear', 'II'), ('thirdyear', 'III')], default='third', max_length=26)),
                ('Score', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
