# Generated by Django 2.0.5 on 2018-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbms_score',
            name='regno',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
